import Footer from "components/Footer";
import SuccesfulStartup from "components/SuccesfulStartup";
import Head from "next/head";
import React, { createContext, useEffect, useReducer } from "react";
import styles from "@/styles/HireUs.module.css";
import HireUsStepOne from "components/pages/HireUsStepOne";
import { useHireUsnavigationReducer } from "hooks/useHireUsNavigation";
import HireUsStepTwo from "components/pages/HireUsStepTwo";
import HireUsStepThree from "components/pages/HireUsStepThree";
import HireUsStepFour from "components/pages/HireUsStepFour";
import HireUsStepFive from "components/pages/HireUsStepFive";
import HireUsCompleted from "components/pages/HireUsCompleted";

export const NavigationContext = createContext();
const pages = [
  { page: <HireUsStepOne /> },
  { page: <HireUsStepTwo /> },
  { page: <HireUsStepThree /> },
  { page: <HireUsStepFour /> },
  { page: <HireUsStepFive /> },
  { page: <HireUsCompleted /> },
];

export default function hireUs() {
  const [navigationState, navigationDispatch] = useReducer(
    useHireUsnavigationReducer,
    { currentNavigationState: 0, formProgress: 0 }
  );
  useEffect(() => {
    console.log(navigationState);
  }, [navigationState]);
  return (
    <>
      <Head>
        <title>Hire Us @ Hackcity Teech Inc</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.png" />
        <link
          href="https://fonts.googleapis.com/css?family=Poppins"
          rel="stylesheet"
        />
      </Head>
      <main className={styles.hireUs}>
        <NavigationContext.Provider
          value={{ navigationState, navigationDispatch }}
        >
          {pages[navigationState.currentNavigationState].page}
        </NavigationContext.Provider>
        <SuccesfulStartup />
        <Footer />
      </main>
    </>
  );
}
