import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import NavBar from 'components/NavBar'
import Banner from 'components/Banner'
import OurExperence from 'components/OurExperence'
import ExperienceQuality from 'components/ExperienceQuality'
import SuccesfulStartup from 'components/SuccesfulStartup'
import OurServices from 'components/OurServices'
import WhyHireUs from 'components/WhyHireUs'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Hackcity Teech Inc</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="main">
          <section className='homeBanner'>
            <NavBar/>
            <Banner/>

          </section>

          <section className='whoWeAre'>
           <OurExperence/>
           <ExperienceQuality/>
           <SuccesfulStartup/>
          </section>

          <section className='ourServiceSection'>
            <OurServices/>
          </section>

          <section className='whyHireUsSection'>
          <span className="experienceTitle">Why Hire Us</span>

              <WhyHireUs/>
          </section>
     
      </main>
    </>
  )
}
